ukm_amb_homepage:
    path:     /
    defaults: { _controller: UKMAmbBundle:Welcome:index }

ukm_amb_profile_homepage:
    path:     /profil/
    defaults: { _controller: UKMAmbBundle:Profile:index }

ukm_amb_join_homepage:
    path:	/bli-ambassador/
    defaults: { _controller: UKMAmbBundle:Join:index }
   
ukm_amb_join_phone:
    path: /bli-ambassador/mobil/
    defaults: { _controller: UKMAmbBundle:Join:phone }
    
ukm_amb_join_register:
    path: /bli-ambassador/connect/
    defaults: { _controller: UKMAmbBundle:Join:connect }
    
ukm_amb_join_address:
    path: /bli-ambassador/velkomstpakke/
    defaults: { _controller: UKMAmbBundle:Join:address }
    
ukm_amb_join_complete:
    path: /bli-ambassador/send_velkomstpakke/
    defaults: { _controller: UKMAmbBundle:Join:complete }
    methods: [POST]

ukm_amb_got_package:
    path: /bli-ambassador/har_pakke/
    defaults: { _controller: UKMAmbBundle:Join:gotPackage }

ukm_amb_mail_test:
    path: /test/mail/
    defaults: { _controller: UKMAmbBundle:Test:mail }

wordpress_page:
    path: /side/{id}/
    defaults: { _controller: UKMAmbBundle:Wordpress:page }
    
wordpress_post:
    path: /innlegg/{year}/{month}/{date}/{id}/
    defaults: { _controller: UKMAmbBundle:Wordpress:post }

wordpress_reset_lastbuild:
    path: /wpcache/reset
    defaults: { _controller: UKMAmbBundle:Wordpress:deleteLastBuild }