services:
    ukm_amb.wordpressCache:
        class: UKMNorge\AmbassadorBundle\Services\WordpressCacheService
        arguments:
            - @service_container

    ukm_amb.wordpressTheme:
        class: UKMNorge\AmbassadorBundle\Services\WordpressThemeService
        arguments:
            - @service_container

    ukm_amb.ambassador:
        class: UKMNorge\AmbassadorBundle\Services\AmbassadorService
        arguments:
            - @service_container
    ukm_amb.season:
        class: UKMNorge\AmbassadorBundle\Services\SeasonService
        arguments:
            - @service_container