# app/config/security.yml (FOSUB)
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        secure_area:
            pattern: ^/
            
            oauth:
                failure_path: /login
                login_path: /login
                check_path: /login
#                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
                     service: MariusMandalUserProvider
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                login_path: /login
#                check_path: /login_check
            logout:
                path: /logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area, roles: ROLE_USER }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
